#Automation
- alias: Set Thermostat Cool Target
  trigger:
    platform: state
    entity_id: input_slider.thermostat_cool_target
  action:
    service: mqtt.publish
    data_template:
      topic: "smartthings/Thermostat/coolingSetpoint"
      retain: true
      payload: '{{ states.input_slider.thermostat_cool_target.state }}'

- alias: Set Thermostat Cool Target Slider
  trigger:
    platform: mqtt
    topic: "smartthings/Thermostat/coolingSetpoint"
  action:
    service: input_slider.select_value
    data_template:
      entity_id: input_slider.thermostat_cool_target
      value: '{{ trigger.payload }}'

- alias: Set Thermostat Heat Target
  trigger:
    platform: state
    entity_id: input_slider.thermostat_heat_target
  action:
    service: mqtt.publish
    data_template:
      topic: "smartthings/Thermostat/heatingSetpoint"
      retain: true
      payload: '{{ states.input_slider.thermostat_heat_target.state }}'

- alias: Set Thermostat Heat Target Slider
  trigger:
    platform: mqtt
    topic: "smartthings/Thermostat/heatingSetpoint"
  action:
    service: input_slider.select_value
    data_template:
      entity_id: input_slider.thermostat_heat_target
      value: '{{ trigger.payload }}'

- alias: Set Thermostat Mode
  trigger:
    platform: state
    entity_id: input_select.thermostat_mode
  action:
    service: mqtt.publish
    data_template:
      topic: "smartthings/Thermostat/thermostatMode"
      retain: true
      payload: '{{ states.input_select.thermostat_mode.state }}'

- alias: Set Thermostat Mode Selector
  trigger:
    platform: mqtt
    topic: "smartthings/Thermostat/thermostatMode"
  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.thermostat_mode
      option: '{{ trigger.payload }}'

- alias: Camera Motion Detection Off when Someone is Home
  trigger:
    platform: state
    entity_id: device_tracker.scott, device_tracker.gabe, device_tracker.marvin
    to: 'home'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: switch.amcrestlrmotion
      state: 'on'
    - condition: time
      after: '00:00:01'
      before: '05:00:00'
  action:
  - service: script.cameras_off
  - service: input_boolean.turn_off
    entity_id: input_boolean.door_notifications

- alias: Door Notifications Off when Someone is Home
  trigger:
    platform: state
    entity_id: device_tracker.scott, device_tracker.gabe, device_tracker.marvin
    to: 'home'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.door_notifications
      state: 'on'
    - condition: time
      after: '00:00:01'
      before: '05:00:00'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.door_notifications

- alias: Send Alert when Door opens
  trigger:
    platform: state
    entity_id: sensor.kitchen_door, sensor.central_door, sensor.front_door, sensor.back_garage_door, sensor.garage_door
    to: 'open'
  condition:
    condition: state
    entity_id: input_boolean.door_notifications
    state: 'on'
  action:
    service: notify.notify
    data_template:
      message: >
        {{ trigger.to_state.attributes.friendly_name }} Opened

- alias: Send Alert when Smoke Detector Detects Smoke
  trigger:
    platform: state
    entity_id: sensor.kitchen_smoke_alarm, sensor.garage_smoke_alarm, sensor.hallway_smoke_alarm
    to: 'smoke detected'
  action:
    service: notify.notify
    data_template:
      message: >
        {{ trigger.to_state.attributes.friendly_name }} Detected Smoke

- alias: Send Alert when Smoke Detector Detects CO
  trigger:
    platform: state
    entity_id: sensor.kitchen_smoke_alarm, sensor.garage_smoke_alarm, sensor.hallway_smoke_alarm
    to: 'carbon monoxide detected'
  action:
    service: notify.notify
    data_template:
      message: >
        {{ trigger.to_state.attributes.friendly_name }} Detected Carbon Monoxide

- alias: Plex Paused
  trigger:
    - platform: state
      entity_id: media_player.scottsplex
      to: 'paused'
      for:
        seconds: 4
  action:
      service: homeassistant.turn_on
      entity_id: light.living_room_light, light.dining_light

- alias: Plex Stopped
  trigger:
    - platform: state
      entity_id: media_player.scottsplex
      to: 'idle'
  action:
      service: homeassistant.turn_on
      entity_id: light.living_room_light, light.dining_light

- alias: Plex playing
  trigger:
    - platform: state
      entity_id: media_player.scottsplex
      to: 'playing'
  action:
      service: homeassistant.turn_off
      entity_id: light.living_room_light, light.dining_light, light.hallway_light

- alias: Garage Lights on when door opens
  trigger:
    platform: state
    entity_id: sensor.central_door, sensor.garage_door
    to: 'open'
  action:
    service: homeassistant.turn_on
    entity_id: light.garage_light

- alias: Hallway Light On at night with Motion
  trigger:
    platform: state
    entity_id: sensor.hallway_motion_sensor
    to: 'motion'
  condition:
    condition: time
    after: '21:00:01'
    before: '06:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.hallway_light
    data:
      brightness: 100

- alias: Hallway Light On during the day with Motion
  trigger:
    platform: state
    entity_id: sensor.hallway_motion_sensor
    to: 'motion'
  condition:
    condition: time
    after: '06:00:01'
    before: '21:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.hallway_light

- alias: Kitchen Light On with Motion
  trigger:
    platform: state
    entity_id: sensor.kitchen_motion_sensor
    to: 'motion'
  action:
    service: homeassistant.turn_on
    entity_id: light.kitchen_light

- alias: Hallway Light Off after 1 minute
  trigger:
    platform: state
    entity_id: sensor.hallway_motion_sensor
    to: 'clear'
    for:
      minutes: 1
  action:
    service: homeassistant.turn_off
    entity_id: light.hallway_light

- alias: Garage Light On with Motion
  trigger:
    platform: state
    entity_id: sensor.garage_motion_sensor
    to: 'motion'
  action:
    service: homeassistant.turn_on
    entity_id: light.garage_light
 
- alias: Garage Light Off after 5 minutes
  trigger:
    platform: state
    entity_id: sensor.garage_motion_sensor
    to: 'clear'
    for:
      minutes: 5
  action:
    service: homeassistant.turn_off
    entity_id: light.garage_light

- alias: Coming Home Lights On
  trigger:
    platform: state
    entity_id: sensor.front_door, sensor.central_door
    to: 'open'
  condition:
    condition: state
    entity_id: input_boolean.entry_lights
    state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: group.insidelights
  - service: input_boolean.turn_on
    entity_id: input_boolean.entry_lights

- alias: Reset Morning Lights Boolean 5am
  trigger:
    platform: time
    after: '05:00:00'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.morning_lights

- alias: Reset Morning Lights Boolean 7am
  trigger:
    platform: time
    after: '07:00:00'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.morning_lights

- alias: Morning Automation
  trigger:
    platform: state
    entity_id: sensor.hallway_motion_sensor
    to: 'motion'
  condition:
    condition: and
    conditions:
    - condition: time
      after: '05:00:00'
    - condition: state
      entity_id: input_boolean.morning_lights
      state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: group.insidelights
  - service: input_boolean.turn_on
    entity_id: input_boolean.morning_lights
  - service: script.cameras_off

- alias: Cameras and Door Notifications on at midnight
  trigger:
    platform: time
    after: '00:00:01'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: sensor.kitchen_motion_sensor
      state: 'clear'
      for:
        minutes: 10
    - condition: state
      entity_id: sensor.hallway_motion_sensor
      state: 'clear'
      for:
        minutes: 10
    - condition: state
      entity_id: media_player.scottsplex
      state: 'stopped'
  action:
  - service: script.cameras_on
  - service: input_boolean.turn_on
    entity_id: input_boolean.door_notifications

- alias: Cameras on at 1am
  trigger:
    platform: time
    after: '01:00:00'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: sensor.kitchen_motion_sensor
      state: 'clear'
      for:
        minutes: 10
    - condition: state
      entity_id: sensor.hallway_motion_sensor
      state: 'clear'
      for:
        minutes: 10
    - condition: state
      entity_id: media_player.scottsplex
      state: 'stopped'
  action:
  - service: script.cameras_on
  - service: input_boolean.turn_on
    entity_id: input_boolean.door_notifications

- alias: Actions when No one is Home
  trigger:
    platform: state
    entity_id: group.all_devices
    to: 'not_home'
    for:
      minutes: 10
  action:
  - service: homeassistant.turn_off
    entity_id: group.all_lights
  - service: input_boolean.turn_off
    entity_id: input_boolean.entry_lights
  - service: script.cameras_on
  - service: input_boolean.turn_on
    entity_id: input_boolean.door_notifications

- alias: Notify that Garage is open after 10pm
  trigger:
    platform: state
    entity_id: sensor.garage_door
    to: 'open'
  condition:
    condition: time
    after: '22:00:00'
    before: '23:59:59'
  action:
    service: notify.notify
    data:
      message: "Garage Door is still open."

- alias: Notify that Garage is open for 30 minutes
  trigger:
    platform: state
    entity_id: cover.garage_door
    to: 'open'
    for:
      minutes: 30
  action:
    service: notify.notify
    data:
      message: "Garage Door has been open 30 minutes."

- alias: Notify if Home-Assistant has an update
  trigger:
  - platform: state
    entity_id: updater.updater
  action:
    service: notify.notify
    data:
      message: "Home-Assistant has an update."