#Cameras
- platform: amcrest
  host: 192.168.1.7
  username: admin
  password: !secret common_password
  stream_source: snapshot
  name: Living Room

- platform: amcrest
  host: 192.168.1.8
  username: admin
  password: !secret common_password
  stream_source: snapshot
  name: Garage

- platform: amcrest
  host: 192.168.1.9
  username: admin
  password: !secret common_password
  stream_source: snapshot
  name: Back Yard

- platform: amcrest
  host: 192.168.1.10
  username: admin
  password: !secret common_password
  stream_source: snapshot
  name: Front Yard