homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 710
  unit_system: imperial
  time_zone: America/New_York
  customize:
    switch.amcrestbackyardmotion:
      emulated_hue: false
    switch.amcrestfrontyardmotion:
      emulated_hue: false
    switch.amcrestgaragemotion:
      emulated_hue: false
    switch.amcrestlrmotion:
      emulated_hue: false
    switch.bedroom_receptacle_switch_13_0:
      emulated_hue: false
    climate.thermostat_cooling_1_12_2:
      friendly_name: Thermostat Cooling
    climate.thermostat_heating_1_12_1:
      friendly_name: Thermostat Heating
    binary_sensor.centralite_3305s_0405562d_1:
      friendly_name: Hallway Motion Sensor Zigbee
    binary_sensor.visonic_mct340_e_0b1219c2_1:
      friendly_name: Front Door Zigbee
    binary_sensor.visonic_mct340_e_0b3ba6c3_1:
      friendly_name: Central Door Zigbee
    binary_sensor.visonic_mct340_e_0b110e25_1:
      friendly_name: Kitchen Door Zigbee
    binary_sensor.visonic_mct340_e_0b112478_1:
      friendly_name: Back Garage Door Zigbee

config:
frontend:
logbook:
updater:
hassio:
#sun:
#discovery:
history:
panel_iframe: !include panels.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automation/
amcrest: !include cameras.yaml
script: !include scripts.yaml
zwave:
  usb_path: /dev/ttyUSB0
  new_entity_ids: true
recorder:
  purge_days: 3
climate:
  platform: zwave
logger:
  default: error
  logs:
    homeassistant.components.switch.template: fatal
    homeassistant.components.sensor.template: error
camera:
 platform: amcrest

zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db

notify:
  platform: pushover
  api_key: !secret pushover_api_key
  user_key: !secret pushover_user_key

http:
  api_password: !secret common_password
  ip_ban_enabled: True
  login_attempts_threshold: 5

emulated_hue:
  host_ip: 192.168.1.3
  listen_port: 80
  expose_by_default: true
  exposed_domains:
  - light
  - switch
  - fan

lutron_caseta:
  host: 192.168.1.5

device_tracker:
  platform: asuswrt
  host: 192.168.1.1
  username: admin
  password: !secret common_password
  track_new_devices: no
  interval_seconds: 30
  consider_home: 30

cover:
  platform: myq
  username: !secret myq_username
  password: !secret myq_password
  type: chamberlain

ifttt:
  key: !secret ifttt_key

media_player:
- platform: plex
  include_non_clients: true
  scan_interval: 5
  show_all_controls: true
  use_custom_entity_ids: false
  use_episode_art: true
- platform: spotify
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret
- platform: cast
  host: 192.168.1.12

input_boolean:
  entry_lights:
    name: Entry Lights
    initial: on
  door_notifications:
    name: Door Notifications
    initial: on
  morning_lights:
    name: Morning Lights
    initial: on
  alarm_set:
    name: Alarm Set
    initial: on
  cloud_timer:
    name: Cloud Timer
    initial: off

light:
  - platform: yeelight
    devices:
      192.168.1.21:
        name: Lightstrip
        transition: 1000
        use_music_mode: True