- platform: mqtt
  name: "Kitchen Light"
  state_topic: "smartthings/Kitchen Light/switch"
  command_topic: "smartthings/Kitchen Light/switch"
  brightness_state_topic: "smartthings/Kitchen Light/level"
  brightness_command_topic: "smartthings/Kitchen Light/level"
  brightness_scale: "100"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Dining Light"
  state_topic: "smartthings/Dining Light/switch"
  command_topic: "smartthings/Dining Light/switch"
  brightness_state_topic: "smartthings/Dining Light/level"
  brightness_command_topic: "smartthings/Dining Light/level"
  brightness_scale: "100"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Hallway Light"
  state_topic: "smartthings/Hallway Light/switch"
  command_topic: "smartthings/Hallway Light/switch"
  brightness_state_topic: "smartthings/Hallway Light/level"
  brightness_command_topic: "smartthings/Hallway Light/level"
  brightness_scale: "100"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Garage Light"
  state_topic: "smartthings/Garage Light/switch"
  command_topic: "smartthings/Garage Light/switch"
  brightness_state_topic: "smartthings/Garage Light/level"
  brightness_command_topic: "smartthings/Garage Light/level"
  brightness_scale: "100"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Bedroom Light"
  state_topic: "smartthings/Bedroom Light/switch"
  command_topic: "smartthings/Bedroom Light/switch"
  brightness_state_topic: "smartthings/Bedroom Light/level"
  brightness_command_topic: "smartthings/Bedroom Light/level"
  brightness_scale: "100"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Living Room Light"
  state_topic: "smartthings/Living Room Light/switch"
  command_topic: "smartthings/Living Room Light/switch"
  brightness_state_topic: "smartthings/Living Room Light/level"
  brightness_command_topic: "smartthings/Living Room Light/level"
  brightness_scale: "100"
  payload_on: "on"
  payload_off: "off"
  retain: true