#Sensors
- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_free
  - type: processor_use
  - type: network_in
    arg: eth0
  - type: network_out
    arg: eth0
  - type: last_boot

- platform: mqtt
  name: "Current Temperature"
  state_topic: "smartthings/Thermostat/temperature"
  retain: true

- platform: mqtt
  name: "Thermostat State"
  state_topic: "smartthings/Thermostat/thermostatOperatingState"
  retain: true

- platform: mqtt
  name: "Heat Target"
  state_topic: "smartthings/Thermostat/heatingSetpoint"
  retain: true

- platform: mqtt
  name: "Cool Target"
  state_topic: "smartthings/Thermostat/coolingSetpoint"
  retain: true

- platform: mqtt
  name: "Thermostat Mode"
  state_topic: "smartthings/Thermostat/thermostatMode"
  retain: true

- platform: mqtt
  name: "Thermostat Fan Mode"
  state_topic: "smartthings/Thermostat/thermostatFanMode"
  retain: true

- platform: mqtt
  name: "Thermostat Humidity"
  state_topic: "smartthings/Thermostat/humidity"
  retain: true

- platform: mqtt
  name: "Hallway Motion Sensor"
  state_topic: "smartthings/Hallway Motion Sensor/motion"
  retain: true
  value_template: '{% if value is equalto "active" %} motion {% elif value is equalto "inactive"%} clear {% else %} failed {% endif %}'

- platform: mqtt
  name: "Garage Motion Sensor"
  state_topic: "smartthings/Garage Motion Sensor/motion"
  retain: true
  value_template: '{% if value is equalto "active" %} motion {% elif value is equalto "inactive"%} clear {% else %} failed {% endif %}'

- platform: mqtt
  name: "Kitchen Motion Sensor"
  state_topic: "smartthings/Kitchen Motion Sensor/motion"
  retain: true
  value_template: '{% if value is equalto "active" %} motion {% elif value is equalto "inactive"%} clear {% else %} failed {% endif %}'

- platform: mqtt
  name: "Front Door"
  state_topic: "smartthings/Front Door/contact"
  retain: true

- platform: mqtt
  name: "Kitchen Door"
  state_topic: "smartthings/Kitchen Door/contact"
  retain: true

- platform: mqtt
  name: "Back Garage Door"
  state_topic: "smartthings/Back Garage Door/contact"
  retain: true

- platform: mqtt
  name: "Central Door"
  state_topic: "smartthings/Central Door/contact"
  retain: true

- platform: mqtt
  name: "Kitchen Smoke Detector"
  state_topic: "smartthings/Kitchen Smoke Alarm/smoke"
  retain: true

- platform: mqtt
  name: "Kitchen Carbon Detector"
  state_topic: "smartthings/Kitchen Smoke Alarm/carbonMonoxide"
  retain: true

- platform: mqtt
  name: "Hallway Smoke Detector"
  state_topic: "smartthings/Hallway Smoke Alarm/smoke"
  retain: true

- platform: mqtt
  name: "Hallway Carbon Detector"
  state_topic: "smartthings/Hallway Smoke Alarm/carbonMonoxide"
  retain: true

- platform: mqtt
  name: "Garage Smoke Detector"
  state_topic: "smartthings/Garage Smoke Alarm/smoke"
  retain: true

- platform: mqtt
  name: "Garage Carbon Detector"
  state_topic: "smartthings/Garage Smoke Alarm/carbonMonoxide"
  retain: true