#Sensors
- platform: darksky
  api_key: 433e7bcdee176830d6af6a63bca5dcf6
  latitude: 35.1166232
  longitude: -85.1380908
  monitored_conditions:
    - precip_intensity

- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_free
  - type: processor_use
  - type: network_in
    arg: eth0
  - type: network_out
    arg: eth0
  - type: last_boot

- platform: template
  sensors:
    hallway_motion:
      friendly_name: "Hallway Motion"
      value_template: '{% if is_state("binary_sensor.centralite_3305s_0405562d_1", "on") %} motion {% elif is_state("binary_sensor.centralite_3305s_0405562d_1", "off") %} clear {% else %} failed {% endif %}'
    porch_motion:
      friendly_name: "Porch Motion"
      value_template: '{% if is_state("binary_sensor.hallway_motion_sensor", "on") %} motion {% elif is_state("binary_sensor.hallway_motion_sensor", "off") %} clear {% else %} failed {% endif %}'
    garage_motion:
      friendly_name: "Garage Motion"
      value_template: '{% if is_state("binary_sensor.garage_motion_sensor", "on") %} motion {% elif is_state("binary_sensor.garage_motion_sensor", "off") %} clear {% else %} failed {% endif %}'
    kitchen_motion:
      friendly_name: "Kitchen Motion"
      value_template: '{% if is_state("binary_sensor.kitchen_motion_sensor", "on") %} motion {% elif is_state("binary_sensor.kitchen_motion_sensor", "off") %} clear {% else %} failed {% endif %}'
    front_door:
      friendly_name: "Front Door"
      value_template: '{% if is_state("binary_sensor.visonic_mct340_e_0b1219c2_1", "on") %} open {% elif is_state("binary_sensor.visonic_mct340_e_0b1219c2_1", "off") %} closed {% else %} failed {% endif %}'
    kitchen_door:
      friendly_name: "Kitchen Door"
      value_template: '{% if is_state("binary_sensor.visonic_mct340_e_0b110e25_1", "on") %} open {% elif is_state("binary_sensor.visonic_mct340_e_0b110e25_1", "off") %} closed {% else %} failed {% endif %}'
    back_garage_door:
      friendly_name: "Back Garage Door"
      value_template: '{% if is_state("binary_sensor.visonic_mct340_e_0b112478_1", "on") %} open {% elif is_state("binary_sensor.visonic_mct340_e_0b112478_1", "off") %} closed {% else %} failed {% endif %}'
    central_door:
      friendly_name: "Central Door"
      value_template: '{% if is_state("binary_sensor.visonic_mct340_e_0b3ba6c3_1", "on") %} open {% elif is_state("binary_sensor.visonic_mct340_e_0b3ba6c3_1", "off") %} closed {% else %} failed {% endif %}'
    kitchen_smoke_detector:
      value_template: >-
          {%- if is_state("sensor.kitchen_smoke_detector_alarm_type", "13") %}
              Idle
          {%- elif is_state("sensor.kitchen_smoke_detector_alarm_type", "1") %}
              Fire Detected
          {%- elif is_state("sensor.kitchen_smoke_detector_alarm_type", "2") %}
              Carbon Monoxide Detected
          {%- elif is_state("sensor.kitchen_smoke_detector_alarm_type", "12") %}
              Alarm Testing
          {% else %}
              Unknown
          {%- endif %}
      friendly_name: "Kitchen Smoke Detector"
    hallway_smoke_detector:
      value_template: >-
          {%- if is_state("sensor.hallway_smoke_detector_alarm_type", "13") %}
              Idle
          {%- elif is_state("sensor.hallway_smoke_detector_alarm_type", "1") %}
              Fire Detected
          {%- elif is_state("sensor.hallway_smoke_detector_alarm_type", "2") %}
              Carbon Monoxide Detected
          {%- elif is_state("sensor.hallway_smoke_detector_alarm_type", "12") %}
              Alarm Testing
          {% else %}
              Unknown
          {%- endif %}
      friendly_name: "Hallway Smoke Detector"
    garage_smoke_detector:
      value_template: >-
          {%- if is_state("sensor.garage_smoke_detector_alarm_type", "13") %}
              Idle
          {%- elif is_state("sensor.garage_smoke_detector_alarm_type", "1") %}
              Fire Detected
          {%- elif is_state("sensor.garage_smoke_detector_alarm_type", "2") %}
              Carbon Monoxide Detected
          {%- elif is_state("sensor.garage_smoke_detector_alarm_type", "12") %}
              Alarm Testing
          {% else %}
              Unknown
          {%- endif %}
      friendly_name: "Garage Smoke Detector"
    garage_smoke_detector_battery:
      friendly_name: 'Garage Smoke Detector Battery'
      value_template: '{{ states.zwave.garage_smoke_detector.attributes.battery_level }}'
      unit_of_measurement: '%'
    hallway_smoke_detector_battery:
      friendly_name: 'Hallway Smoke Detector Battery'
      value_template: '{{ states.zwave.hallway_smoke_detector.attributes.battery_level }}'
      unit_of_measurement: '%'
    kitchen_smoke_detector_battery:
      friendly_name: 'Kitchen Smoke Detector Battery'
      value_template: '{{ states.zwave.kitchen_smoke_detector.attributes.battery_level }}'
      unit_of_measurement: '%'
    thermostat_battery:
      friendly_name: 'Thermostat Battery'
      value_template: '{{ states.zwave.thermostat.attributes.battery_level }}'
      unit_of_measurement: '%'