#Switches
- platform: command_line
  switches:
    amcrestlrmotion:
      command_on: 'curl -k -u admin:[PASSWORD] "http://192.168.1.7/cgi-bin/configManager.cgi?action=setConfig&MotionDetect\[0\].Enable=true"'
      command_off: 'curl -k -u admin:[PASSWORD] "http://192.168.1.7/cgi-bin/configManager.cgi?action=setConfig&MotionDetect\[0\].Enable=false"'
      command_state: 'curl -k --silent -u admin:[PASSWORD] "http://192.168.1.7/cgi-bin/configManager.cgi?action=getConfig&name=MotionDetect\[0\].Enable" | sed "s/^.*\(.\{5\}\)$/\1/"'
      value_template: '{{ value == "true" }}'
      friendly_name: Living Room Motion Detection
    amcrestgaragemotion:
      command_on: 'curl -k -u admin:[PASSWORD] "http://192.168.1.8/cgi-bin/configManager.cgi?action=setConfig&MotionDetect\[0\].Enable=true"'
      command_off: 'curl -k -u admin:[PASSWORD] "http://192.168.1.8/cgi-bin/configManager.cgi?action=setConfig&MotionDetect\[0\].Enable=false"'
      command_state: 'curl -k --silent -u admin:[PASSWORD] "http://192.168.1.8/cgi-bin/configManager.cgi?action=getConfig&name=MotionDetect\[0\].Enable" | sed "s/^.*\(.\{5\}\)$/\1/"'
      value_template: '{{ value == "true" }}'
      friendly_name: Garage Motion Dection
    amcrestbackyardmotion:
      command_on: 'curl -k -u admin:[PASSWORD] "http://192.168.1.9/cgi-bin/configManager.cgi?action=setConfig&MotionDetect\[0\].Enable=true"'
      command_off: 'curl -k -u admin:[PASSWORD] "http://192.168.1.9/cgi-bin/configManager.cgi?action=setConfig&MotionDetect\[0\].Enable=false"'
      command_state: 'curl -k --silent -u admin:[PASSWORD] "http://192.168.1.9/cgi-bin/configManager.cgi?action=getConfig&name=MotionDetect\[0\].Enable" | sed "s/^.*\(.\{5\}\)$/\1/"'
      value_template: '{{ value == "true" }}'
      friendly_name: Back Yard Motion Detection
    amcrestfrontyardmotion:
      command_on: 'curl -k -u admin:[PASSWORD] "http://192.168.1.10/cgi-bin/configManager.cgi?action=setConfig&MotionDetect\[0\].Enable=true"'
      command_off: 'curl -k -u admin:[PASSWORD] "http://192.168.1.10/cgi-bin/configManager.cgi?action=setConfig&MotionDetect\[0\].Enable=false"'
      command_state: 'curl -k --silent -u admin:[PASSWORD] "http://192.168.1.10/cgi-bin/configManager.cgi?action=getConfig&name=MotionDetect\[0\].Enable" | sed "s/^.*\(.\{5\}\)$/\1/"'
      value_template: '{{ value == "true" }}'
      friendly_name: Front Yard Motion Detection