#Lights Automation
- id: 7amBedroom
  alias: Bedroom Light on and Noise Machine off at 7am
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: device_tracker.scott
      state: 'home'
    - condition: state
      entity_id: input_boolean.alarm_set
      state: 'on'
  action:
    service: script.morning_alarm

- id: LightstripOffAtMidnight
  alias: Lightstrip off at midnight if Plex idle
  trigger:
    platform: time
    at: '00:00:01'
  condition:
    condition: state
    entity_id: media_player.scottsplex
    state: 'idle'
  action:
    service: light.turn_off
    entity_id: light.lightstrip

- id: GarageLightsOnWhenDoorOpens
  alias: Garage Lights On When Door Opens
  trigger:
    platform: state
    entity_id: sensor.central_door, cover.garage_door
    to: 'open'
  condition:
    condition: state
    entity_id: light.garage_light
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: light.garage_light
    data:
        brightness: 255

- id: GarageLightOnWithMotion
  alias: Garage Light On With Motion
  trigger:
    platform: state
    entity_id: sensor.garage_motion
    to: 'motion'
  condition:
    condition: state
    entity_id: light.garage_light
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: light.garage_light
    data:
        brightness: 255
 
- id: GarageLightOffAfter5Mins
  alias: Garage Light Off after 5 Minutes
  trigger:
    platform: state
    entity_id: sensor.garage_motion
    to: 'clear'
    for:
      minutes: 5
  condition:
    condition: state
    entity_id: light.garage_light
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: light.garage_light

- id: HallwayLightOnWithMotion-Night
  alias: Hallway Light On At Night With Motion
  trigger:
    platform: state
    entity_id: sensor.hallway_motion
    to: 'motion'
  condition:
    condition: and
    conditions:
    - condition: time
      after: '21:00:01'
      before: '06:00:00'
    - condition: state
      entity_id: light.hallway_light
      state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: light.hallway_light
    data:
        brightness: 50

- id: HallwayLightOnWithMotion-Day
  alias: Hallway Light On During The Day With Motion
  trigger:
    platform: state
    entity_id: sensor.hallway_motion
    to: 'motion'
  condition:
    condition: and
    conditions:
    - condition: time
      after: '06:00:01'
      before: '21:00:00'
    - condition: state
      entity_id: light.hallway_light
      state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: light.hallway_light
    data:
        brightness: 255

- id: HallwayLightOffNoMotion
  alias: Hallway Light Off after No Motion
  trigger:
    platform: state
    entity_id: sensor.hallway_motion
    to: 'clear'
    for:
      seconds: 5
  condition:
    condition: state
    entity_id: light.hallway_light
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: light.hallway_light

- id: KitchenLightOnWithMotion
  alias: Kitchen Light On With Motion
  trigger:
    platform: state
    entity_id: sensor.kitchen_motion
    to: 'motion'
  condition:
    condition: state
    entity_id: light.kitchen_light
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: light.kitchen_light
    data:
        brightness: 255

- id: ComingHomeLightsOn
  alias: Coming Home Lights On
  trigger:
    platform: state
    entity_id: sensor.front_door, sensor.central_door
    to: 'open'
  condition:
    condition: state
    entity_id: input_boolean.entry_lights
    state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: group.insidelights
    data:
        brightness: 255
  - service: input_boolean.turn_on
    entity_id: input_boolean.entry_lights

- id: ResetMorningLightsBoolean5am
  alias: Reset Morning Lights Boolean 5am
  trigger:
    platform: time
    at: '05:00:00'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.morning_lights

- alias: Reset Morning Lights Boolean 7am
  trigger:
    platform: time
    at: '07:00:00'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.morning_lights