#Security Automation
- id: MorningAutomation
  alias: Morning Automation
  trigger:
    platform: state
    entity_id: sensor.hallway_motion
    to: 'motion'
  condition:
    condition: and
    conditions:
    - condition: time
      after: '05:00:00'
    - condition: state
      entity_id: input_boolean.morning_lights
      state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: group.insidelights
    data:
      brightness: 255
  - service: input_boolean.turn_on
    entity_id: input_boolean.morning_lights
  - service: script.inside_cameras_off

- id: InsideCamerasAndDoorNotificationsOnAtMidnight
  alias: Inside Cameras And Door Notifications On At Midnight
  trigger:
    platform: time
    at: '00:00:01'
  action:
  - service: script.inside_cameras_on
  - service: input_boolean.turn_on
    entity_id: input_boolean.door_notifications

- id: ActionsWhenEveryoneLeaves
  alias: Actions When Everyone Leaves
  trigger:
    platform: state
    entity_id: group.all_devices
    to: 'not_home'
    for:
      minutes: 10
  action:
  - service: homeassistant.turn_off
    entity_id: group.all_lights
  - service: input_boolean.turn_off
    entity_id: input_boolean.entry_lights
  - service: script.inside_cameras_on
  - service: input_boolean.turn_on
    entity_id: input_boolean.door_notifications

- id: InsideCamerasOffWhenSomeoneArrivesHome
  alias: Inside Cameras Off When Someone Arrives Home
  trigger:
    platform: state
    entity_id: device_tracker.scott, device_tracker.gabe, device_tracker.mathia
    to: 'home'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: switch.amcrestlrmotion
      state: 'on'
    - condition: time
      after: '05:00:00'
      before: '00:00:01'
  action:
  - service: script.inside_cameras_off
  - service: input_boolean.turn_off
    entity_id: input_boolean.door_notifications

- id: DoorNotificationsOffWhenSomeoneArrivesHome
  alias: Door Notifications Off When Someone Arrives Home
  trigger:
    platform: state
    entity_id: device_tracker.scott, device_tracker.gabe, device_tracker.mathia
    to: 'home'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.door_notifications
      state: 'on'
    - condition: time
      after: '05:00:00'
      before: '00:00:01'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.door_notifications

- id: OutsideCamerasOnWhenStopsRaining
  alias: Outside Cameras On When Stops Raining
  trigger:
    platform: state
    entity_id: sensor.dark_sky_precip_intensity
    to: '0'
    for:
      minutes: 10
  condition:
    condition: or
    conditions:
    - condition: time
      after: '00:00:01'
      before: '06:00:00'
    - condition: state
      entity_id: group.all_devices
      state: not_home
  action:
  - service: script.outside_inside_cameras_on

- id: OutsideCamerasOffWhenStartsRaining
  alias: Outside Cameras Off When Starts Raining
  trigger:
    platform: state
    entity_id: sensor.dark_sky_precip_intensity
    from: '0'
  action:
  - service: script.outside_inside_cameras_off