#Thermostat Automation
- alias: Set Thermostat Cool Target
  trigger:
    platform: state
    entity_id: input_slider.thermostat_cool_target
  action:
    service: mqtt.publish
    data_template:
      topic: "smartthings/Thermostat/coolingSetpoint"
      retain: true
      payload: '{{ states.input_slider.thermostat_cool_target.state }}'

- alias: Set Thermostat Cool Target Slider
  trigger:
    platform: mqtt
    topic: "smartthings/Thermostat/coolingSetpoint"
  action:
    service: input_slider.select_value
    data_template:
      entity_id: input_slider.thermostat_cool_target
      value: '{{ trigger.payload }}'

- alias: Set Thermostat Heat Target
  trigger:
    platform: state
    entity_id: input_slider.thermostat_heat_target
  action:
    service: mqtt.publish
    data_template:
      topic: "smartthings/Thermostat/heatingSetpoint"
      retain: true
      payload: '{{ states.input_slider.thermostat_heat_target.state }}'

- alias: Set Thermostat Heat Target Slider
  trigger:
    platform: mqtt
    topic: "smartthings/Thermostat/heatingSetpoint"
  action:
    service: input_slider.select_value
    data_template:
      entity_id: input_slider.thermostat_heat_target
      value: '{{ trigger.payload }}'

- alias: Set Thermostat Mode
  trigger:
    platform: state
    entity_id: input_select.thermostat_mode
  action:
    service: mqtt.publish
    data_template:
      topic: "smartthings/Thermostat/thermostatMode"
      retain: true
      payload: '{{ states.input_select.thermostat_mode.state }}'

- alias: Set Thermostat Mode Selector
  trigger:
    platform: mqtt
    topic: "smartthings/Thermostat/thermostatMode"
  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.thermostat_mode
      option: '{{ trigger.payload }}'